### ISSUE TITLE
Running as root without --no-sandbox is not supported

### ISSUE THREAD

**Issue by Muratcol** [daybrush/scenejs#73]
OS: Ubuntu 18.04
Node: v10.24.1

Hello,

I'm having the following issue while trying to render an HTML file:
```
// Command: render -i /tmp/8c7a99b9-4417-49ac-891d-7246c426c72e.html -o /tmp/8c7a99b9-4417-49ac-891d-7246c426c72e_rendered.mp4

stdout: Open Page:  file:///home/muratcolyaran/projects/microservices-google-cloud/index.html

stdout: Start Rendering

stderr: Error: Failed to launch chrome!
[0616/111525.046404:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/muratcolyaran/projects/microservices-google-cloud/node_modules/@scenejs/render/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.helper.addEventListener (/home/muratcolyaran/projects/microservices-google-cloud/node_modules/@scenejs/render/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I know I need to start chromium headless but I couldn't find how could I send options to the puppeteer.

**Comment by daybrush** [comment]
https://github.com/daybrush/scenejs-render/issues/9
